@echo off
setlocal enabledelayedexpansion

rem 打包带hutb插件的虚幻编辑器
rem Run it through a cmd with the x64 Visual C++ Toolset enabled.

set LOCAL_PATH=%~dp0
set FILE_N=-[%~n0]:

rem Print batch params (debug purpose)
echo %FILE_N% [Batch params]: %*

rem ============================================================================
rem -- Parse arguments ---------------------------------------------------------
rem ============================================================================

:: TODO: custom through command parameter
set offline_dir=C:\jenkins\

set BUILD_UE4_EDITOR=false
set LAUNCH_UE4_EDITOR=false
:: 是否打包UE4编辑器
set PACKAGE_UE4_EDITOR=false
set REMOVE_INTERMEDIATE=false
set USE_CARSIM=false
set USE_CHRONO=false
set USE_UNITY=true
set CARSIM_STATE="CarSim OFF"
set CHRONO_STATE="Chrono OFF"
set UNITY_STATE="Unity ON"
set AT_LEAST_WRITE_OPTIONALMODULES=false
set EDITOR_FLAGS=""
set USE_ROS2=false
set ROS2_STATE="Ros2 OFF"

:arg-parse
echo %1
if not "%1"=="" (
    if "%1"=="--editor-flags" (
        set EDITOR_FLAGS=%2
        shift
    )
    if "%1"=="--build" (
        set BUILD_UE4_EDITOR=true
    )
    if "%1"=="--launch" (
        set LAUNCH_UE4_EDITOR=true
    )
    if "%1"=="--package" (
        set PACKAGE_UE4_EDITOR=true
        goto package_editor
    )
    if "%1"=="--clean" (
        set REMOVE_INTERMEDIATE=true
    )
    if "%1"=="--carsim" (
        set USE_CARSIM=true
    )
    if "%1"=="--chrono" (
        set USE_CHRONO=true
    )
    if "%1"=="--ros2" (
        set USE_ROS2=true
    )
    if "%1"=="--no-unity" (
        set USE_UNITY=false
    )
    if "%1"=="--at-least-write-optionalmodules" (
        set AT_LEAST_WRITE_OPTIONALMODULES=true
    )
    if "%1"=="-h" (
        goto help
    )
    if "%1"=="--help" (
        goto help
    )
    shift
    goto arg-parse
)
rem remove quotes from arguments
set EDITOR_FLAGS=%EDITOR_FLAGS:"=%

if %REMOVE_INTERMEDIATE% == false (
    if %LAUNCH_UE4_EDITOR% == false (
        if %BUILD_UE4_EDITOR% == false (
            if %AT_LEAST_WRITE_OPTIONALMODULES% == false (
                goto help
            )
        )
    )
)

rem Get Unreal Engine root path
if not defined UE4_ROOT (
    set KEY_NAME="HKEY_LOCAL_MACHINE\SOFTWARE\EpicGames\Unreal Engine"
    set VALUE_NAME=InstalledDirectory
    for /f "usebackq tokens=1,2,*" %%A in (`reg query !KEY_NAME! /s /reg:64`) do (
        if "%%A" == "!VALUE_NAME!" (
            set UE4_ROOT=%%C
        )
    )
    if not defined UE4_ROOT goto error_unreal_no_found
)
if not "%UE4_ROOT:~-1%"=="\" set UE4_ROOT=%UE4_ROOT%\

rem Set the visual studio solution directory
rem
set UE4_PROJECT_FOLDER=%ROOT_PATH:/=\%Unreal\CarlaUE4\
pushd "%UE4_PROJECT_FOLDER%"

rem Clear binaries and intermediates generated by the build system
rem
if %REMOVE_INTERMEDIATE% == true (
    rem Remove directories
    for %%G in (
        "%UE4_PROJECT_FOLDER%Binaries",
        "%UE4_PROJECT_FOLDER%Build",
        "%UE4_PROJECT_FOLDER%Saved",
        "%UE4_PROJECT_FOLDER%Intermediate",
        "%UE4_PROJECT_FOLDER%Plugins\Carla\Binaries",
        "%UE4_PROJECT_FOLDER%Plugins\Carla\Intermediate",
        "%UE4_PROJECT_FOLDER%Plugins\HoudiniEngine\",
        "%UE4_PROJECT_FOLDER%.vs"
    ) do (
        if exist %%G (
            echo %FILE_N% Cleaning %%G
            rmdir /s/q %%G
        )
    )

    rem Remove files
    for %%G in (
        "%UE4_PROJECT_FOLDER%CarlaUE4.sln"
    ) do (
        if exist %%G (
            echo %FILE_N% Cleaning %%G
            del %%G
        )
    )
)


:package_editor
    echo Package UE4 editor...

:: 打包：开发资产的版本 使用每个仓库的dev分支，当仓库干净时同步最新的修改
:: （都是覆盖性）
:: 如果 Build\UE4Carla\hutb_editor 目录不存在则创建。:/=\ 表示使用\代替/
set package_root=%INSTALLATION_DIR:/=\%UE4Carla\
set editor_dir=%package_root%hutb_editor\
:: 如果存在则删除

:: if exist "%package_root%" (
::     :: delete all files (exclude directory)
::     del /f /s /q %package_root%\hutb_editor\*
::     :: remove empty directory
::     rd /s /q %package_root%\hutb_editor\
:: )
:: echo Create package directory: mkdir %editor_dir%
:: mkdir %editor_dir%


:: copy launch_carla_editor.bat
xcopy %ROOT_PATH:/=\%Util\BuildTools\launch_hutb_editor.bat %editor_dir% /e /y /h /r /q
:: 解压 software.zip 中的 4 个依赖软件：cmake、dotnet、make、python3_7 到 hutb_editor 目录下
if exist "%offline_dir%software\" (
    echo xcopy %offline_dir%software\  %editor_dir%  /e /y /h /r /q
    xcopy %offline_dir%software\  %editor_dir%  /e /y /h /r /q
) else (
    echo TODO: online install 7zip, CMake, dotnet, GnuWin32, Python37
)


:: copy UnrealEngine source code (including dependency)
if exist "%offline_dir%software\" (
    if not exist "%ROOT_PATH:/=\%Build\UE4Carla\hutb_editor\unreal\" (
        xcopy %offline_dir%UnrealEngine\  %ROOT_PATH:/=\%Build\UE4Carla\hutb_editor\unreal\  /e /y /h /r /q
    ) else (
        echo Exist UnrealEngine code, skip copy it.
    )
) else (
    echo TODO: download UnrealEngine source code and execute Setup.bat, GenerateProjectFiles.bat
)


:: copy hutb source code
if not exist "%ROOT_PATH:/=\%Build\UE4Carla\hutb_editor\carla1\" (
    xcopy %offline_dir%hutb\  %ROOT_PATH:/=\%Build\UE4Carla\hutb_editor\carla1\  /e /y /h /r /q
    :: copy Unreal plugin
    xcopy %offline_dir%StreetMap\  %ROOT_PATH:/=\%Build\UE4Carla\hutb_editor\carla1\Unreal\CarlaUE4\Plugins\StreetMap  /e /y /h /r /q
) else (
    echo Exist hutb source code, skip copy it.
)



if exist "%programfiles%\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" (
    call "%programfiles%\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
) else (
    call "%programfiles%\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
)
:: copy required dependency and asset (download only, not compile)
set cur_dir=%CD%
echo Current directory: %CD%
:: cd D:\work\workspace\carla\Build\UE4Carla\hutb_editor\carla1
cd %ROOT_PATH:/=\%Build\UE4Carla\hutb_editor\carla1
make setup ARGS="--download_only"
:: return to previous directory
cd %cur_dir%
echo Return to previous directory: %CD%


:: compress to hutb_editor.zip
:: TODO: add UnrealEngine doc and hutb doc
:: 7zip\7z.exe x vs2019.7z -o.
call %ROOT_PATH:/=\%Build\UE4Carla\hutb_editor\7zip\7z.exe  a  %ROOT_PATH:/=\%Build\UE4Carla\hutb_editor.zip  %ROOT_PATH:/=\%Build\UE4Carla\hutb_editor\*


goto good_exit

rem ============================================================================
rem -- Messages and Errors -----------------------------------------------------
rem ============================================================================

:help
    echo Build LibCarla.
    echo "Usage: %FILE_N% [-h^|--help] [--build] [--launch] [--clean]"
    goto good_exit

:error_build
    echo.
    echo %FILE_N% [ERROR] There was a problem building CarlaUE4.
    echo %FILE_N%         Please go to "Carla\Unreal\CarlaUE4", right click on
    echo %FILE_N%         "CarlaUE4.uproject" and select:
    echo %FILE_N%         "Generate Visual Studio project files"
    echo %FILE_N%         Open de generated "CarlaUE4.sln" and try to manually compile it
    echo %FILE_N%         and check what is causing the error.
    goto bad_exit

:good_exit
    endlocal
    exit /b 0

:bad_exit
    endlocal
    exit /b %errorlevel%

:error_unreal_no_found
    echo.
    echo %FILE_N% [ERROR] Unreal Engine not detected
    goto bad_exit
