"""
Diff two MJCF schema snapshots to find new/removed elements and attributes.

Usage:
    python Scripts/diff_schema.py Scripts/mjcf_schema_snapshot.json new_snapshot.json

The "new" snapshot can be generated by extracting from the latest MuJoCo
xml_native_reader.cc, or manually updating the JSON.

Output: list of added/removed elements and attributes, ready for implementation.
"""

import json
import sys
from pathlib import Path


def diff_lists(old: list, new: list) -> tuple[list, list]:
    """Returns (added, removed) items."""
    old_set = set(old)
    new_set = set(new)
    return sorted(new_set - old_set), sorted(old_set - new_set)


def diff_schemas(old: dict, new: dict) -> dict:
    """Diff two schema snapshots. Returns structured diff."""
    results = {"added_elements": [], "removed_elements": [], "attribute_changes": []}

    old_keys = set(k for k in old if not k.startswith("_"))
    new_keys = set(k for k in new if not k.startswith("_"))

    # Top-level element additions/removals
    for elem in sorted(new_keys - old_keys):
        results["added_elements"].append(elem)
    for elem in sorted(old_keys - new_keys):
        results["removed_elements"].append(elem)

    # Attribute-level diffs for shared elements
    for elem in sorted(old_keys & new_keys):
        old_elem = old[elem]
        new_elem = new[elem]

        if isinstance(old_elem, dict) and isinstance(new_elem, dict):
            # Check "attrs" key
            if "attrs" in old_elem and "attrs" in new_elem:
                added, removed = diff_lists(old_elem["attrs"], new_elem["attrs"])
                if added or removed:
                    results["attribute_changes"].append({
                        "element": elem,
                        "field": "attrs",
                        "added": added,
                        "removed": removed
                    })

            # Check nested dicts (e.g., actuator_types, equality, etc.)
            for key in set(list(old_elem.keys()) + list(new_elem.keys())):
                if key in ("attrs", "children", "wrap_types", "targets"):
                    continue
                old_val = old_elem.get(key, [])
                new_val = new_elem.get(key, [])
                if isinstance(old_val, list) and isinstance(new_val, list):
                    added, removed = diff_lists(old_val, new_val)
                    if added or removed:
                        results["attribute_changes"].append({
                            "element": f"{elem}.{key}",
                            "field": "attrs",
                            "added": added,
                            "removed": removed
                        })

            # Check "children" key
            if "children" in old_elem and "children" in new_elem:
                added, removed = diff_lists(old_elem["children"], new_elem["children"])
                if added or removed:
                    results["attribute_changes"].append({
                        "element": elem,
                        "field": "children",
                        "added": added,
                        "removed": removed
                    })

        elif isinstance(old_elem, list) and isinstance(new_elem, list):
            added, removed = diff_lists(old_elem, new_elem)
            if added or removed:
                results["attribute_changes"].append({
                    "element": elem,
                    "field": "items",
                    "added": added,
                    "removed": removed
                })

    return results


def print_diff(diff: dict):
    """Pretty-print the diff results."""
    if diff["added_elements"]:
        print("\n=== NEW ELEMENTS ===")
        for elem in diff["added_elements"]:
            print(f"  + {elem}")

    if diff["removed_elements"]:
        print("\n=== REMOVED ELEMENTS ===")
        for elem in diff["removed_elements"]:
            print(f"  - {elem}")

    if diff["attribute_changes"]:
        print("\n=== ATTRIBUTE CHANGES ===")
        for change in diff["attribute_changes"]:
            elem = change["element"]
            if change["added"]:
                for attr in change["added"]:
                    print(f"  + {elem}.{attr}")
            if change["removed"]:
                for attr in change["removed"]:
                    print(f"  - {elem}.{attr}")

    if not any(diff.values()):
        print("\nNo changes detected. Schemas are identical.")


def main():
    if len(sys.argv) < 3:
        print("Usage: python diff_schema.py <old_snapshot.json> <new_snapshot.json>")
        return

    old_path = Path(sys.argv[1])
    new_path = Path(sys.argv[2])

    with open(old_path) as f:
        old = json.load(f)
    with open(new_path) as f:
        new = json.load(f)

    print(f"Old: {old.get('_meta', {}).get('mujoco_version', '?')} ({old_path.name})")
    print(f"New: {new.get('_meta', {}).get('mujoco_version', '?')} ({new_path.name})")

    diff = diff_schemas(old, new)
    print_diff(diff)

    # Summary
    total_added = len(diff["added_elements"]) + sum(len(c["added"]) for c in diff["attribute_changes"])
    total_removed = len(diff["removed_elements"]) + sum(len(c["removed"]) for c in diff["attribute_changes"])
    print(f"\nTotal: +{total_added} additions, -{total_removed} removals")


if __name__ == "__main__":
    main()
