name: hutb Windows CI/CD

on: 
  push:
  pull_request:


jobs:
  windows-dev:
    name: Windows CI/CD
    timeout-minutes: 1440
    runs-on: self-hosted:windows
    env:
      UE4_ROOT: C:\workspace\UnrealEngine
      VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: setup
        run: |
          call setEnv64.bat
          git update-index --skip-worktree Unreal/CarlaUE4/CarlaUE4.uproject
          make setup ARGS="--chrono"
        shell: cmd

      - name: build
        run: |
          call setEnv64.bat
          make plugins
        shell: cmd

      - name: retrieve content
        run: |
          call setEnv64.bat
          call Update.bat
        shell: cmd

      - name: package
        run: |
          call setEnv64.bat
          make package ARGS="--chrono"
        shell: cmd

      - name: test
        run: |
          call setEnv64.bat
          make check.PythonAPI
          make check.smoke
        shell: cmd
